language: php
php: ["7.2"]
sudo: false
dist: trusty

install:
- "wget -O - https://poggit.pmmp.io/res/travisInstall.sh | bash -s - || true"

script:
- "if [ -f ${TRAVIS_BUILD_DIR}/../PocketMine/unstaged/EggWars.phar ] ; then wget -O - https://poggit.pmmp.io/res/travisScript.sh | bash -s - EggWars EggWars ; else true ; fi"