name: EggWars
version: 0.1 - InDev
api: [3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3]
author: GamakCZ
description: EggWars minigame plugin
main: EggWars\EggWars

commands:
  ew:
    description: EggWars commands
    aliases: ["eggwars", "eggw", "ewars"]
