name: EggWars
api: 3.0.0-ALPHA5
version: 0.1-DEV
author: GamakCZ
main: EggWars\EggWars

commands:
  eggwars:
    aliases: [ew]
    description: Main EggWars Command
    
permissions:
  ew.cmd.help:
    description: Permission for /ew help
    default: op
  ew.cmd.addlevel:
    description: Permission for /ew addlevel
    default: op
  ew.cmd.setlevel:
    description: Permission for /ew setlevel
    default: op
  ew.cmd.setlobby:
    description: Permission for /ew setlobby
    default: op
