name: EggWars
version: DEV
main:EggWars\EggWars
description: EggWars MiniGame
author: GamakCZ
website: bit.do/gamcz

api:
- 1.13.0
- 1.8.0
- 2.0.0

commands:
  EggWars:
    aliases: ew
    description: default EggWars Command

permissions:
  ew.cmd.help:
    default: op
  
  ew.cmd.ophelp:
    default: op
