---
enable: "false"
startTime: "30"
gameTime: "600"
restartTime: "20"
teamsToStart: "2"
playersPerTeam: "2"
level: "EggWars"
teams: []
#  red:
#    players:
#    color: "ยง4"
#    spawn:
#    egg:
#  blue:
#    players:
#    color: "ยง9"
#    spawn:
#    egg:
...