name: EggWars
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
version: 1.0.0-beta1
author: VixikCZ
main: eggwars\EggWars
description: EggWars minigame plugin
website: https://github.com/GamakCZ/EggWars
load: POSTWORLD

permissions:
  ew.cmd:
    description: Permission for ALL EggWars Commands
    default: op
    children:
      ew.cmd.vote:
        default: true
        description: Permission for /vote
      ew.cmd.team:
        default: true
        description: Permission for /team
      ew.cmd.help:
        default: op
        description: Permission to /ew help
      ew.cmd.create:
        default: op
        description: Permission to /ew create
      ew.cmd.arenas:
        default: op
        description: Permission to /ew arenas
      ew.cmd.set:
        default: op
        description: Permission to /ew set
      ew.cmd.info:
        default: true
        description: Permission to /ew info
      ew.cmd.shop:
        default: true
        description: Permission to /ew shop
      ew.cmd.level:
        default: op
        description: Permissions for level commands
        children:
          ew.cmd.level.add:
            default: op
            description: Permission to /ew level add
          ew.cmd.level.set:
            default: op
            description: Permission to /ew level set
