name: EggWars
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
version: 0.1
author: VixikCZ
main: eggwars\EggWars
description: EggWars minigame plugin

permissions:
  ew.cmd:
    description: Permission for ALL EggWars Commands
    default: op
    childern:
      ew.cmd.help:
        default: op
        description: Permission to /ew help
      ew.cmd.create:
        default: op
        description: Permission to /ew create
      ew.cmd.set:
        default: op
        description: Permission to /ew set
      ew.cmd.join:
        default: true
        description: Permission to join the test arena
