name: EggWars
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
version: 0.1
author: VixikCZ
main: eggwars\EggWars
description: EggWars minigame plugin

permissions:
  ew.cmd:
    description: Permission for ALL EggWars Commands
